# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate_gradlew:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Validate gradlew
        uses: actions/checkout@v2
    
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Queue in GitHub Build Check
      uses: LouisBrunner/checks-action@v0.1.0
      with:
        token: ${{ secrets.TOKEN }}
        name: Build
        conclusion: neutral
        status: queued

    - name: Queue in GitHub Test Check
      uses: LouisBrunner/checks-action@v0.1.0
      with:
        token: ${{ secrets.TOKEN }}
        name: Test
        conclusion: neutral
        status: queued

    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Cache .gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Start GitHub Build Check
      uses: LouisBrunner/checks-action@v0.1.0
      with:
        token: ${{ secrets.TOKEN }}
        name: Build
        conclusion: neutral
        status: in_progress

    - name: Build with Gradle
      id: build
      continue-on-error: true
      run: ./gradlew build

    - name: Successful GitHub Build Check
      uses: LouisBrunner/checks-action@v0.1.0
      if: ${{ steps.build.outcome == success }}
      with:
        token: ${{ secrets.TOKEN }}
        name: Build
        conclusion: success
        status: completed
        
    - name: Failed GitHub Build Check
      uses: LouisBrunner/checks-action@v0.1.0
      if: ${{ steps.build.outcome == failure }}
      with:
        token: ${{ secrets.TOKEN }}
        name: Build
        conclusion: failure
        status: completed   

    - name: Start GitHub Test Check
      uses: LouisBrunner/checks-action@v0.1.0
      with:
        token: ${{ secrets.TOKEN }}
        name: Test
        conclusion: neutral
        status: in_progress

    - name: Run tests
      id: test
      run: ./gradlew test  
              
    - name: Successful GitHub Test Check
      uses: LouisBrunner/checks-action@v0.1.0
      if: ${{ steps.test.outcome == success }}
      with:
        token: ${{ secrets.TOKEN }}
        name: Test
        conclusion: success
        status: completed

    - name: Failed GitHub Test Check
      uses: LouisBrunner/checks-action@v0.1.0
      if: ${{ steps.test.outcome == failure }}
      with:
        token: ${{ secrets.TOKEN }}
        name: Test
        conclusion: failure
        status: completed 
